FUCK stupid shitty rails errors.
Apparently it was rising shitty

> ArgumentError: A sender (Return-Path, Sender or From) required to send a message

error because of this.